### ISSUE TITLE
torchopenl3 error

### ISSUE THREAD

**Issue by jorshi** [neuralaudio/hear-baseline#28]
```
Importing hearbaseline.torchopenl3
Traceback (most recent call last):
  File "/home/jshier/anaconda3/bin/hear-validator", line 33, in <module>
    sys.exit(load_entry_point('hearvalidator', 'console_scripts', 'hear-validator')())
  File "/home/jshier/development/neuralaudio/hear-validator/hearvalidator/validate.py", line 449, in main
    ValidateModel(args.module, args.model, device=args.device)()
  File "/home/jshier/development/neuralaudio/hear-validator/hearvalidator/validate.py", line 46, in __call__
    self.import_model()
  File "/home/jshier/development/neuralaudio/hear-validator/hearvalidator/validate.py", line 72, in import_model
    self.module = importlib.import_module(self.module_name)
  File "/home/jshier/anaconda3/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/jshier/development/neuralaudio/hear-baseline/hearbaseline/torchopenl3.py", line 9, in <module>
    import torchopenl3
  File "/home/jshier/development/torchopenl3/torchopenl3/__init__.py", line 1, in <module>
    from .core import get_audio_embedding
  File "/home/jshier/development/torchopenl3/torchopenl3/core.py", line 7, in <module>
    import torch.tensor as T
ModuleNotFoundError: No module named 'torch.tensor'
```

**Comment by turian** [comment]
@jorshi what version of pytorch are you on? I remember we had something similar for torchsynth, do you remember what we did?
